### ISSUE TITLE
Postfix integration 

### ISSUE THREAD

**Issue by buzzzo** [ColumPaget/Mimeguard#1]
Is it possible to integrate mimeguard at smtp level?

**Comment by ColumPaget** [comment]
What's needed to acheive this? I use it with an smtp server, but it's my own one so It's written to make this easy.

**Comment by buzzzo** [comment]
The use case is when you have a mail relay in front of your real mail server.
So you don't need to have a path with mail files , but rather the mail is scanned in real time by a content filter installed on the smtp gateway server

**Comment by ColumPaget** [comment]
hmm, so we'd read the main in on stdin? Or is there some other means of doing that? I'll look into 'content filters'.

**Comment by buzzzo** [comment]
You could implement it as content filter (smtp proxy) or as milter .

**Comment by ColumPaget** [comment]
Hi,

in the end I went for smtp proxy, as that's the easiest solution to code, and also I think the one that's compatible with the greatest number of server types. Release v3.0 has this feature. Tested it with my own systems, but not with postfix yet.
